### ISSUE TITLE
Pridať možnosť skopírovania url na inzerát

### ISSUE THREAD

**Issue by VOJAKIS** [Voltrifrodec/bazarik-fe#33]

**Comment by Voltrifrodec** [comment]
## Návrh
- aktuálne je problém riešený pomocou `navigator.clipboard.writeText()`
- možné riešenie do budúcnosti pomocou [`CDK Clipboard`](https://material.angular.io/cdk/clipboard/api)

## Známe chyby
- odkaz na kopírovanie nie je proporcionálne správne na pravej strane
![image](https://user-images.githubusercontent.com/69749982/233799223-2613eee9-011b-4097-b752-d992c0d951a4.png)
