### ISSUE TITLE
FEATURE: Rýchla navigácia vo footeri sa nenachádza v strede

### ISSUE THREAD

**Issue by VOJAKIS** [Voltrifrodec/bazarik-fe#52]
![image](https://user-images.githubusercontent.com/50027263/232312744-8f3ec0ce-da83-4acb-a058-5dde4ca9571e.png)

**Comment by Voltrifrodec** [comment]
Toto nie je bug, ale zámer -- je to na boku len preto, ak by sa pridávali nové sekciu do `footer` komponentu (napr. opis stránky, disclaimer, odkazy na použ. podporu, ...).

**Comment by VOJAKIS** [comment]
> Toto nie je bug, ale zámer -- je to na boku len preto, ak by sa pridávali nové sekciu do `footer` komponentu (napr. opis stránky, disclaimer, odkazy na použ. podporu, ...).

Toto je možné vyriešiť cez aditívne pridávanie cez flexbox, aj s tým, že sa budú deti nachádzať v strede footera.
![image](https://user-images.githubusercontent.com/50027263/232599853-79078b49-620e-4c78-b493-f019466b2176.png)
`<div class="d-flex justify-content-center">...</div>`
([https://getbootstrap.com/docs/4.0/utilities/flex/](url))
