### ISSUE TITLE
Posunúť zoznam podkategórií a podkategórií bližšie ku názvu podkategórie a podpodkategórie, resp.

### ISSUE THREAD

**Issue by VOJAKIS** [Voltrifrodec/bazarik-fe#60]
![image](https://user-images.githubusercontent.com/50027263/232604308-538a9e13-5c31-4aee-90a8-e61b0a6126ee.png)
->
![image](https://user-images.githubusercontent.com/50027263/232604688-ef14e96b-fe36-4c50-ba3f-39f730a66772.png)

**Comment by Voltrifrodec** [comment]
Napadli ma ešte tieto zmeny:
- medzera medzi položkami je príliš veľká, stačí zmenšiť o 50% (`gap: 2vmin` na `gap: 1vmin`)
